### ISSUE TITLE
Mirror no longer be accessible

### ISSUE THREAD

**Issue by mingkai0812** [ashumkin/apt-cyg#7]
Hey guys,

since 1 february 2015 the open mirror "mirror.mcs.anl.gov" is unavailable.
Quote "The following websites will no longer be accessible from the Internet:
* http://mirror.anl.gov
* http://mirror.mcs.anl.gov
* http://mirror.ipv6.anl.gov
This applies to access via the HTTP, FTP, and rsync protocols." 

Maybe you would change the default config.

friendly sincerly

**Comment by ashumkin** [comment]
Thank you!
